server:
  port: 5000

spring:
  application:
    name: first-demo
  profiles:
      active: test

  datasource:
#    url: jdbc:h2:./data/Spring
#    username: DatabaseH2
    url: jdbc:h2:mem:InMemory
    username: MemH2
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

app:
  version: 1.0.0

