spring:
  datasource:
    url: jdbc:h2:mem:InMemory
    username: MemH2
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
      path: /h2-console

logging:
  level:
    root: warn
    sql: warn
