spring:
  datasource:
    url: jdbc:h2:mem:InMemory
    username: MemH2
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: debug
    sql: debug
#    org:
#      hibernate: error
#      springframework:
#        web: debug
#    com:
#      liutyk:
#        first_demo: trace
#  file:
#    name: logs/first_demo.log
#    path: logs/
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB
